import type { AnalysisResult } from './api';

const NS = 'http://www.w3.org/2000/svg';
export function renderVisualization(container: HTMLElement, result: AnalysisResult): void {
  container.replaceChildren();
  const header = document.createElement('div'); header.className = 'plot-header'; const title = document.createElement('span'); title.className = 'plot-title'; title.textContent = 'Character movement'; const subtitle = document.createElement('span'); subtitle.className = 'plot-subtitle'; subtitle.textContent = `${result.scenes.length} scenes · first appearance order`; header.append(title, subtitle); container.append(header);
  const body = document.createElement('div'); body.className = 'plot-canvas'; const svg = document.createElementNS(NS, 'svg'); svg.setAttribute('viewBox', `0 0 900 ${Math.max(180, result.characters.length * 48)}`); svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', 'Character appearances across scenes');
  const summary = document.createElement('p'); summary.className = 'plot-summary'; summary.textContent = result.characters.map((character) => `${character.display_name}: ${result.appearances.filter((item) => item.character_id === character.id).map((item) => item.scene_id).join(', ') || 'absent'}`).join(' · ');
  for (let index = 0; index < result.scenes.length; index += 1) { const line = document.createElementNS(NS, 'line'); line.setAttribute('x1', String(40 + index * (820 / Math.max(1, result.scenes.length - 1)))); line.setAttribute('x2', line.getAttribute('x1')!); line.setAttribute('y1', '15'); line.setAttribute('y2', String(Math.max(160, result.characters.length * 48))); line.setAttribute('class', 'plot-grid'); svg.append(line); }
  for (const [row, character] of result.characters.entries()) { const points = result.visualization.paths[character.id] ?? []; if (!points.length) continue; const path = document.createElementNS(NS, 'path'); const d = points.map(([sceneIndex]) => `${40 + sceneIndex * (820 / Math.max(1, result.scenes.length - 1))},${35 + row * 48}`).join(' L '); path.setAttribute('d', `M ${d}`); path.setAttribute('stroke', result.visualization.colors[character.id]); path.setAttribute('class', 'flow flow-speaking'); path.setAttribute('fill', 'none'); svg.append(path); for (const [sceneIndex] of points) { const circle = document.createElementNS(NS, 'circle'); circle.setAttribute('cx', String(40 + sceneIndex * (820 / Math.max(1, result.scenes.length - 1)))); circle.setAttribute('cy', String(35 + row * 48)); circle.setAttribute('r', '5'); circle.setAttribute('fill', result.visualization.colors[character.id]); circle.setAttribute('class', 'plot-node'); svg.append(circle); } }
  body.append(svg); container.append(body, summary);
}
